language: r

warnings_are_errors: true

sudo: required

cache: packages

r:
 - oldrel
 - release
 - devel

env:
 global:
   - CRAN: http://cran.rstudio.com

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    - bob@rud.is
