# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert an MGRS string to latitude/longitude
#'
#' @md
#' @param MGRS an MGRS string
#' @param degrees convert to degrees? Default: `TRUE`
#' @export
#' @examples
#' mgrs_to_latlng("15TWG0000049776")
mgrs_to_latlng <- function(MGRS, degrees = TRUE) {
    .Call('mgrs_mgrs_to_latlng', PACKAGE = 'mgrs', MGRS, degrees)
}

#' Convert latitude/longitude to MGRS string
#'
#' @md
#' @param latitude,longitude coordinates
#' @param degrees are latitude/longitude in degrees? Default: `TRUE`
#' @param precision 0:5; level of precision for the conversion. Default `5`
#' @export
#' @examples
#' latlng_to_mgrs(42, -93)
latlng_to_mgrs <- function(latitude, longitude, degrees = TRUE, precision = 5L) {
    .Call('mgrs_latlng_to_mgrs', PACKAGE = 'mgrs', latitude, longitude, degrees, precision)
}

#' Convert UTM to MGRS
#'
#' @md
#' @param zone 1:60
#' @param hemisphere South (`S`) or North (`N`)
#' @param easting,northing easting (X) / northing (Y) (meters)
#' @param precision 0:5; level of precision for the conversion. Default `5`
#' @export
#' @examples
#' utm_to_mgrs(48, "N", 377299, 1483035)
utm_to_mgrs <- function(zone, hemisphere, easting, northing, precision = 5L) {
    .Call('mgrs_utm_to_mgrs', PACKAGE = 'mgrs', zone, hemisphere, easting, northing, precision)
}

#' Convert MGRS to UTM
#'
#' @md
#' @param MGRS an MGRS string
#' @return `data.frame`
#' @export
#' @examples
#' mgrs_to_utm("48PUV7729883034")
mgrs_to_utm <- function(mgrs_string) {
    .Call('mgrs_mgrs_to_utm', PACKAGE = 'mgrs', mgrs_string)
}

#' Convert UPS to MGRS
#'
#' @md
#' @param hemisphere South (`S`) or North (`N`)
#' @param easting,northing easting (X) / northing (Y) (meters)
#' @param precision 0:5; level of precision for the conversion. Default `5`
#' @export
#' @examples
#' ups_to_mgrs("N", 2426773, 1530125)
ups_to_mgrs <- function(hemisphere, easting, northing, precision = 5L) {
    .Call('mgrs_ups_to_mgrs', PACKAGE = 'mgrs', hemisphere, easting, northing, precision)
}

#' Convert MGRS to UPS
#'
#' @md
#' @param MGRS an MGRS string
#' @return `data.frame`
#' @export
#' @examples
#' mgrs_to_ups("ZGC2677330125")
mgrs_to_ups <- function(mgrs_string) {
    .Call('mgrs_mgrs_to_ups', PACKAGE = 'mgrs', mgrs_string)
}

#' Convert UPS to Latitude/Longitude
#'
#' @md
#' @param hemisphere South (`S`) or North (`N`)
#' @param easting,northing easting (X) / northing (Y) (meters)
#' @param degrees convert to degrees? Default: `TRUE`
#' @export
#' @examples
#' ups_to_latlng("N", 2426773, 1530125)
ups_to_latlng <- function(hemisphere, easting, northing, degrees = TRUE) {
    .Call('mgrs_ups_to_latlng', PACKAGE = 'mgrs', hemisphere, easting, northing, degrees)
}

#' Convert UTM to Latitude/Longitude
#'
#' @md
#' @param zone 1:60
#' @param hemisphere South (`S`) or North (`N`)
#' @param easting,northing easting (X) / northing (Y) (meters)
#' @param degrees convert to degrees? Default: `TRUE`
#' @export
#' @examples
#' utm_to_latlng(48, "N", 377299, 1483035)
utm_to_latlng <- function(zone, hemisphere, easting, northing, degrees = TRUE) {
    .Call('mgrs_utm_to_latlng', PACKAGE = 'mgrs', zone, hemisphere, easting, northing, degrees)
}

