# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert an MGRS string to latitude/longitude
#'
#' @md
#' @param MGRS an MGRS string
#' @param degrees convert to degrees? Default: `TRUE`
#' @export
#' @examples
#' mgrs_to_latlng("15TWG0000049776")
mgrs_to_latlng <- function(MGRS, degrees = TRUE) {
    .Call('mgrs_mgrs_to_latlng', PACKAGE = 'mgrs', MGRS, degrees)
}

#' Convert latitude/longitude to MGRS string
#'
#' @md
#' @param latitude,longitude coordinates
#' @param degrees are latitude/longitude in degrees? Default: `TRUE`
#' @param precision level of precision for the conversion. Default `5`
#' @export
#' @examples
#' latlng_to_mgrs(42, -93)
latlng_to_mgrs <- function(latitude, longitude, degrees = TRUE, precision = 5L) {
    .Call('mgrs_latlng_to_mgrs', PACKAGE = 'mgrs', latitude, longitude, degrees, precision)
}

